### ISSUE TITLE
stdout event ?

### ISSUE THREAD

**Issue by smolleyes** [cojs/child-process#5]
hi

if i want to use something like thsi for exemple 

`pv file.tgz | tar xzf - -C target_directory`

wich return in live 

`1.16MB 0:00:20 [6.06MB/s] [==================>               ] 55%  ETA 0:00:37`

how can i yield a spawn and get the live output from stdout or stderr like normal spawn ?

thanks

**Comment by smolleyes** [comment]
i tried 

```
var co = require('co')
var spawn = require('co-child-process')
var fs = require('fs')

co(function* () {
  var t = yield unzip()
})

function * unzip() {
   var stream = fs.createReadStream("/home/sylvain/Documents/imgtmp/photos.zip")
   var out = yield spawn('pv',['-','|','unzip-stream','/tmp']).pump(stream)
}
```

but no success, output is 

```
/tmp/node_modules/co-child-process/lib/index.js:53
    function onoutdata(chunk) {
                      ^

RangeError: Invalid string length
    at Socket.onoutdata (/tmp/node_modules/co-child-process/lib/index.js:53:23)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:529:20)

```

**Comment by NickHeiner** [comment]
I'm not sure what the problem is, and I don't have a whole lot of time to investigate. You may be better off just using `child_process` directly.
